/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZeminKaplamaRouteImport } from './routes/zemin-kaplama'
import { Route as YesilCatiZeminleriRouteImport } from './routes/yesil-cati-zeminleri'
import { Route as SurmeIzolasyonRouteImport } from './routes/surme-izolasyon'
import { Route as ReferanslarRouteImport } from './routes/referanslar'
import { Route as ProjelerRouteImport } from './routes/projeler'
import { Route as PolyureaRouteImport } from './routes/polyurea'
import { Route as PoliuretanRouteImport } from './routes/poliuretan'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HaberlerRouteImport } from './routes/haberler'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjelerIndexRouteImport } from './routes/projeler.index'
import { Route as HaberlerIndexRouteImport } from './routes/haberler.index'
import { Route as SayfaSlugRouteImport } from './routes/sayfa.$slug'
import { Route as ProjelerSlugRouteImport } from './routes/projeler.$slug'
import { Route as HaberlerSlugRouteImport } from './routes/haberler.$slug'

const ZeminKaplamaRoute = ZeminKaplamaRouteImport.update({
  id: '/zemin-kaplama',
  path: '/zemin-kaplama',
  getParentRoute: () => rootRouteImport,
} as any)
const YesilCatiZeminleriRoute = YesilCatiZeminleriRouteImport.update({
  id: '/yesil-cati-zeminleri',
  path: '/yesil-cati-zeminleri',
  getParentRoute: () => rootRouteImport,
} as any)
const SurmeIzolasyonRoute = SurmeIzolasyonRouteImport.update({
  id: '/surme-izolasyon',
  path: '/surme-izolasyon',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferanslarRoute = ReferanslarRouteImport.update({
  id: '/referanslar',
  path: '/referanslar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerRoute = ProjelerRouteImport.update({
  id: '/projeler',
  path: '/projeler',
  getParentRoute: () => rootRouteImport,
} as any)
const PolyureaRoute = PolyureaRouteImport.update({
  id: '/polyurea',
  path: '/polyurea',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliuretanRoute = PoliuretanRouteImport.update({
  id: '/poliuretan',
  path: '/poliuretan',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HaberlerRoute = HaberlerRouteImport.update({
  id: '/haberler',
  path: '/haberler',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerIndexRoute = ProjelerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjelerRoute,
} as any)
const HaberlerIndexRoute = HaberlerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HaberlerRoute,
} as any)
const SayfaSlugRoute = SayfaSlugRouteImport.update({
  id: '/sayfa/$slug',
  path: '/sayfa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerSlugRoute = ProjelerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjelerRoute,
} as any)
const HaberlerSlugRoute = HaberlerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HaberlerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/haberler': typeof HaberlerRouteWithChildren
  '/iletisim': typeof IletisimRoute
  '/poliuretan': typeof PoliuretanRoute
  '/polyurea': typeof PolyureaRoute
  '/projeler': typeof ProjelerRouteWithChildren
  '/referanslar': typeof ReferanslarRoute
  '/surme-izolasyon': typeof SurmeIzolasyonRoute
  '/yesil-cati-zeminleri': typeof YesilCatiZeminleriRoute
  '/zemin-kaplama': typeof ZeminKaplamaRoute
  '/haberler/$slug': typeof HaberlerSlugRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/sayfa/$slug': typeof SayfaSlugRoute
  '/haberler/': typeof HaberlerIndexRoute
  '/projeler/': typeof ProjelerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/iletisim': typeof IletisimRoute
  '/poliuretan': typeof PoliuretanRoute
  '/polyurea': typeof PolyureaRoute
  '/referanslar': typeof ReferanslarRoute
  '/surme-izolasyon': typeof SurmeIzolasyonRoute
  '/yesil-cati-zeminleri': typeof YesilCatiZeminleriRoute
  '/zemin-kaplama': typeof ZeminKaplamaRoute
  '/haberler/$slug': typeof HaberlerSlugRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/sayfa/$slug': typeof SayfaSlugRoute
  '/haberler': typeof HaberlerIndexRoute
  '/projeler': typeof ProjelerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/haberler': typeof HaberlerRouteWithChildren
  '/iletisim': typeof IletisimRoute
  '/poliuretan': typeof PoliuretanRoute
  '/polyurea': typeof PolyureaRoute
  '/projeler': typeof ProjelerRouteWithChildren
  '/referanslar': typeof ReferanslarRoute
  '/surme-izolasyon': typeof SurmeIzolasyonRoute
  '/yesil-cati-zeminleri': typeof YesilCatiZeminleriRoute
  '/zemin-kaplama': typeof ZeminKaplamaRoute
  '/haberler/$slug': typeof HaberlerSlugRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/sayfa/$slug': typeof SayfaSlugRoute
  '/haberler/': typeof HaberlerIndexRoute
  '/projeler/': typeof ProjelerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeri'
    | '/haberler'
    | '/iletisim'
    | '/poliuretan'
    | '/polyurea'
    | '/projeler'
    | '/referanslar'
    | '/surme-izolasyon'
    | '/yesil-cati-zeminleri'
    | '/zemin-kaplama'
    | '/haberler/$slug'
    | '/projeler/$slug'
    | '/sayfa/$slug'
    | '/haberler/'
    | '/projeler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeri'
    | '/iletisim'
    | '/poliuretan'
    | '/polyurea'
    | '/referanslar'
    | '/surme-izolasyon'
    | '/yesil-cati-zeminleri'
    | '/zemin-kaplama'
    | '/haberler/$slug'
    | '/projeler/$slug'
    | '/sayfa/$slug'
    | '/haberler'
    | '/projeler'
  id:
    | '__root__'
    | '/'
    | '/galeri'
    | '/haberler'
    | '/iletisim'
    | '/poliuretan'
    | '/polyurea'
    | '/projeler'
    | '/referanslar'
    | '/surme-izolasyon'
    | '/yesil-cati-zeminleri'
    | '/zemin-kaplama'
    | '/haberler/$slug'
    | '/projeler/$slug'
    | '/sayfa/$slug'
    | '/haberler/'
    | '/projeler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  HaberlerRoute: typeof HaberlerRouteWithChildren
  IletisimRoute: typeof IletisimRoute
  PoliuretanRoute: typeof PoliuretanRoute
  PolyureaRoute: typeof PolyureaRoute
  ProjelerRoute: typeof ProjelerRouteWithChildren
  ReferanslarRoute: typeof ReferanslarRoute
  SurmeIzolasyonRoute: typeof SurmeIzolasyonRoute
  YesilCatiZeminleriRoute: typeof YesilCatiZeminleriRoute
  ZeminKaplamaRoute: typeof ZeminKaplamaRoute
  SayfaSlugRoute: typeof SayfaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zemin-kaplama': {
      id: '/zemin-kaplama'
      path: '/zemin-kaplama'
      fullPath: '/zemin-kaplama'
      preLoaderRoute: typeof ZeminKaplamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yesil-cati-zeminleri': {
      id: '/yesil-cati-zeminleri'
      path: '/yesil-cati-zeminleri'
      fullPath: '/yesil-cati-zeminleri'
      preLoaderRoute: typeof YesilCatiZeminleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surme-izolasyon': {
      id: '/surme-izolasyon'
      path: '/surme-izolasyon'
      fullPath: '/surme-izolasyon'
      preLoaderRoute: typeof SurmeIzolasyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referanslar': {
      id: '/referanslar'
      path: '/referanslar'
      fullPath: '/referanslar'
      preLoaderRoute: typeof ReferanslarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeler': {
      id: '/projeler'
      path: '/projeler'
      fullPath: '/projeler'
      preLoaderRoute: typeof ProjelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polyurea': {
      id: '/polyurea'
      path: '/polyurea'
      fullPath: '/polyurea'
      preLoaderRoute: typeof PolyureaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poliuretan': {
      id: '/poliuretan'
      path: '/poliuretan'
      fullPath: '/poliuretan'
      preLoaderRoute: typeof PoliuretanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haberler': {
      id: '/haberler'
      path: '/haberler'
      fullPath: '/haberler'
      preLoaderRoute: typeof HaberlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeler/': {
      id: '/projeler/'
      path: '/'
      fullPath: '/projeler/'
      preLoaderRoute: typeof ProjelerIndexRouteImport
      parentRoute: typeof ProjelerRoute
    }
    '/haberler/': {
      id: '/haberler/'
      path: '/'
      fullPath: '/haberler/'
      preLoaderRoute: typeof HaberlerIndexRouteImport
      parentRoute: typeof HaberlerRoute
    }
    '/sayfa/$slug': {
      id: '/sayfa/$slug'
      path: '/sayfa/$slug'
      fullPath: '/sayfa/$slug'
      preLoaderRoute: typeof SayfaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeler/$slug': {
      id: '/projeler/$slug'
      path: '/$slug'
      fullPath: '/projeler/$slug'
      preLoaderRoute: typeof ProjelerSlugRouteImport
      parentRoute: typeof ProjelerRoute
    }
    '/haberler/$slug': {
      id: '/haberler/$slug'
      path: '/$slug'
      fullPath: '/haberler/$slug'
      preLoaderRoute: typeof HaberlerSlugRouteImport
      parentRoute: typeof HaberlerRoute
    }
  }
}

interface HaberlerRouteChildren {
  HaberlerSlugRoute: typeof HaberlerSlugRoute
  HaberlerIndexRoute: typeof HaberlerIndexRoute
}

const HaberlerRouteChildren: HaberlerRouteChildren = {
  HaberlerSlugRoute: HaberlerSlugRoute,
  HaberlerIndexRoute: HaberlerIndexRoute,
}

const HaberlerRouteWithChildren = HaberlerRoute._addFileChildren(
  HaberlerRouteChildren,
)

interface ProjelerRouteChildren {
  ProjelerSlugRoute: typeof ProjelerSlugRoute
  ProjelerIndexRoute: typeof ProjelerIndexRoute
}

const ProjelerRouteChildren: ProjelerRouteChildren = {
  ProjelerSlugRoute: ProjelerSlugRoute,
  ProjelerIndexRoute: ProjelerIndexRoute,
}

const ProjelerRouteWithChildren = ProjelerRoute._addFileChildren(
  ProjelerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  HaberlerRoute: HaberlerRouteWithChildren,
  IletisimRoute: IletisimRoute,
  PoliuretanRoute: PoliuretanRoute,
  PolyureaRoute: PolyureaRoute,
  ProjelerRoute: ProjelerRouteWithChildren,
  ReferanslarRoute: ReferanslarRoute,
  SurmeIzolasyonRoute: SurmeIzolasyonRoute,
  YesilCatiZeminleriRoute: YesilCatiZeminleriRoute,
  ZeminKaplamaRoute: ZeminKaplamaRoute,
  SayfaSlugRoute: SayfaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
